### ISSUE TITLE
6_object_wrap/napi - Destructor not called?

### ISSUE THREAD

**Issue by hokiedsp** [nodejs/abi-stable-node-addon-examples#17] opened 2018-03-22 13:19 UTC
Hi,

I've been toying with these examples for sometime (as my introduction to node.js from c++ side) and noticed something peculiar that I'm not sure is the expected behavior.

In Example 6 (N-API), I cannot confirm that the created c++ objects are ever destructed. Here is what I've done:

At the top of `myobject.cc`, I added

```c++
#include <fstream>
std::ofstream os("test.txt",std::fstream::out); // defined globally
```

Then, in MyObject's constructor and destructor as well as in `New()` and `Destructor()` member functions I inserted at the top of each function:

```c++
os << "MyObject::XXX" << std::endl;  // XXX is 'MyObject', '~MyObject', 'New' or 'Destructor'
```

I expect executing `node ./addon.js` creates `test.txt` with 2 sets of the 4 unique `MyObject::XXX` lines. (In my novice node.js eyes, it should create 2 instances of the c++ class.) However, the generated `test.txt` looks like

```
MyObject::New
MyObject::MyObject
MyObject::New
MyObject::MyObject
MyObject::New
MyObject::MyObject
MyObject::New
MyObject::MyObject
```

This output suggests 4 c++ instantiations and none of them being destructed. Is this a bug or lack of my understanding of how things work in this framework?

Thanks
Kesh

**Comment by mhdawson** [comment] 2018-03-29 20:29
This line in Multiply I believe creates a new instance:

```
  status = napi_new_instance(env, cons, kArgCount, argv, &instance);
```

So I think that would explain 3 creates in addition to the one from `var obj = new addon.MyObject(10);`

In terms of no destruction, that should only happen when the JavaScript object is collected by the GC and there is no guarantee when that will happen or that it will happen before the program terminates.

**Comment by hokiedsp** [comment] 2018-03-30 00:43
@mhdawson - Thanks for your reply. Yeah, I've done a little more research on this destructer issue since and learned that the garbage collection is not running in node.js by design. Yikes.

Could the API documentation include a note on all the functions with `napi_finalize` argument that the callback may never get called? 

FYI, I was able to explicitly destruct 2 instances that has assigned variable names `obj` and `newobj` by adding

```javascript
delete obj;
delete newobj;

function forceGC() {
  if (global.gc) {
    global.gc();
  } else {
    console.warn('No GC hook! Start your program as `node --expose-gc ./addon.js`.');
  }
}

forceGC();
```

at the end of `addon.js` and run the example by `--expose-gc ./addon`. The other two apparently are lost completely.

**Comment by mhdawson** [comment] 2018-04-03 16:08
@hokiedsp a comment would make sense.  Do you want to submit a PR for that or should I?

In terms of the 2 that are not run, they would if the gc needed the space. Java had an option to run finalizers on exit, would have to look to see if V8 has the same.  Most often it does not matter as when you are existing you are going to release all memory anyway.

**Comment by yw662** [comment] 2018-04-04 03:45
btw, I have a question that, in the destructor of 6_object_wrap/napi,
```js
void MyObject::Destructor(napi_env env, void* nativeObject, void* /*finalize_hint*/) {
  reinterpret_cast<MyObject*>(nativeObject)->~MyObject();
}
````
do we should really do
`native->~native();`
instead of
`delete native;`
?

**Comment by yw662** [comment] 2018-04-04 04:04
@mhdawson 
> Most often it does not matter as when you are exiting you are going to release all memory anyway.

Absolutely not. Remember nodejs is often used as daemon. People do not want daemon die.

**Comment by bnoordhuis** [comment] 2018-04-04 09:05
What @mhdawson means is that the operating system reclaims memory when a process exits.  There's no point in manual cleanup right before exit when the OS does it too (and is faster too.)

**Comment by yw662** [comment] 2018-04-04 09:08
of course process release all resources when die, but, what I mean is, daemons never and should never die.

Can you cleanup memory leaks of systemd by kill and restart it?

**Comment by bnoordhuis** [comment] 2018-04-04 09:12
It sounds like you may be confusing two things.  As long as Node.js is running the garbage collector tracks and reclaims objects; no special action is needed.  @mhdawson's comment was strictly about process exit.

**Comment by hokiedsp** [comment] 2018-04-04 13:26
@yw662 - To your initial comment on Destruct, yeah, I agree it should read

```c++
delete reinterpret_cast<MyObject*>(nativeObject);
```

Otherwise, the allocated memory for nativeObject instance won't be returned to the heap. At least that's how I understand the process. [link](https://stackoverflow.com/questions/677653/does-delete-call-the-destructor)

**Comment by hokiedsp** [comment] 2018-04-04 22:26
@mhdawson  - 
> a comment PR 

If you could take care of it, that would be great. (I don't even know where to find the API documentation repo).

>  Most often it does not matter as when you are existing you are going to release all memory anyway.

As Node.js being a server-side script, this makes sense (scripts are running as daemon). I'm learning Node.js to develop an Electron app, so I should move on and pay attention to how the Electron performs GC.

Before I close, I have one more question. I'm going to assume that the finalize will never be called and manually destruct a native object, say with a `myObject.Close()` function. What is the proper procedure to release the native class instance from the wrapping Node object?

Looking at API doc, it appears that I need to call `napi_remove_wrap()` in native `Close()` implementation to do this. Is this all it takes? Also, is there a way to "reattach" the native object to that Node object?

Thanks

**Comment by noserati** [comment] 2018-08-31 04:58
Seems to be relevant to this thread,  in the [6_object_wrap](https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/6_object_wrap/node-addon-api) example, if you add a simple destructor it doesn't get called, even with `delete` and `global.gc()`:

    ~MyObject()
    {
      std::cout << "~MyObject";
    }

For now I have to rely upon the manual `Close` pattern.

**Comment by fpelliccioni** [comment] 2019-01-20 00:02
> @mhdawson - Thanks for your reply. Yeah, I've done a little more research on this destructer issue since and learned that the garbage collection is not running in node.js by design. Yikes.

Hello!

Do you have a link/reference where I can confirm your assertion? (I meant to "learned that the garbage collection is not running in node.js by design")

Thanks!

**Comment by mhdawson** [comment] 2019-01-30 18:11
@hokiedsp I think this can be closed now.  If I don't hear from you I'll go ahead and close it.

**Closed** 2019-01-30 18:11 UTC
